name: bloodfinder
description: "Donate blood, Save life"
publish_to: 'none' 

version: 1.0.0+5

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1

  go_router: ^17.0.0
  google_fonts: ^6.3.1

  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  intl: ^0.20.2
  url_launcher: ^6.3.2
  share_plus: ^12.0.0

#
  firebase_messaging: ^16.0.1
  http: ^1.5.0
  flutter_local_notifications: ^19.4.1
  path_provider: ^2.1.5
  googleapis_auth: ^2.0.0


  in_app_update: ^4.2.3
  flutter_image_compress: ^2.4.0
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  fluttertoast: ^9.0.0
  app_links: ^6.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
    android: "launcher_icon"
    image_path: "assets/images/logo.png"
    min_sdk_android: 21


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/data/bloodfinder.json

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
